export const categoryIcons: Record<string, string> = {
  "Ăn uống": "restaurant",
  "Y tế": "medkit",
  "Lương": "cash",
  "Thưởng": "trophy",
  "Đi lại": "car",
  "Giải trí": "game-controller",
  "Mua sắm": "cart",
  "Freelance": "laptop",
  "Kinh doanh": "briefcase",
  "Hóa đơn": "document-text",
  "Giáo dục": "school",
  "Quà tặng": "gift",
  "Du lịch": "airplane",
  "Tiền nhà": "home",
  "Tiền lương": "wallet",
  "Chi tiêu hàng": "cash",
  "Quần áo": "shirt",
  "Mỹ phẩm": "color-palette",
  "Phí giao lưu": "people",
  "Tiền điện": "flash",
  "Phí liên lac": "call",
  "Tiền phụ cấp": "cash",
  "Tiền thưởng": "trophy",
  "Thu nhập phụ": "wallet",
  "Thu nhập tạm" : "wallet", 
  "Đầu tư": "trending-up",
  "Cho thuê": "home",
};
